//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public System.Guid MedicineId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Medicine Medicine { get; set; }
    }
}
